#pragma once

#define LED_NUM_LOCK_PIN C7
#define LED_SCROLL_LOCK_PIN D4
#define LED_CAPS_LOCK_PIN D5

#ifdef AUDIO_ENABLE
  #define AUDIO_PIN B7
  #define AUDIO_CLICKY
  #define STARTUP_SONG SONG(TERMINAL_SOUND)
  #define GOODBYE_SONG SONG(TERMINAL_SOUND)
  #define AG_NORM_SONG SONG(TERMINAL_SOUND)
  #define AG_SWAP_SONG SONG(TERMINAL_SOUND)
  #define CG_NORM_SONG SONG(TERMINAL_SOUND)
  #define CG_SWAP_SONG SONG(TERMINAL_SOUND)
  #define MUSIC_ON_SONG SONG(TERMINAL_SOUND)
  #define MUSIC_OFF_SONG SONG(TERMINAL_SOUND)
  #define CHROMATIC_SONG SONG(TERMINAL_SOUND)
  #define GUITAR_SONG SONG(TERMINAL_SOUND)
  #define VIOLIN_SONG SONG(TERMINAL_SOUND)
  #define MAJOR_SONG SONG(TERMINAL_SOUND)
#endif
